name: vnc
services:
    centos-xfce-vnc:
        ports:
            - 5901:5901
            - 6901:6901
        image: consol/centos-xfce-vnc
        privileged: true
        user: "0"
        volumes: 
          - /mnt/app2/home/docker:/mnt/app/home
        devices:
          - "/dev/sg34:/dev/sg34"
          - "/dev/sg35:/dev/sg35"
          - "/dev/st0:/dev/st0"
          - "/dev/nst0:/dev/nst0"
